#!/usr/bin/env bash
# OpenResolve setup script
# Generates a secure JWT secret and starts the app.
# Usage: ./setup.sh [--port 3000] [--password yourpassword]

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────
HOST_PORT=3000
ADMIN_PASSWORD="openresolve"

# ── Parse args ───────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --port)     HOST_PORT="$2";     shift 2 ;;
    --password) ADMIN_PASSWORD="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: ./setup.sh [--port 3000] [--password yourpassword]"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo ""
echo "  ╔══════════════════════════════╗"
echo "  ║     OpenResolve Setup        ║"
echo "  ╚══════════════════════════════╝"
echo ""

# ── Check docker compose is available ────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "  ✗ Docker not found. Install Docker Desktop or Docker Engine first."
  echo "    https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
  echo "  ✗ 'docker compose' not available. Please update Docker to a recent version."
  exit 1
fi

# ── Generate or reuse JWT secret ─────────────────────────────────────
ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo "  ℹ  Found existing .env — reusing settings."
  echo "     Delete .env and re-run to start fresh."
else
  echo "  → Generating secure JWT secret..."

  # Try openssl first, fall back to /dev/urandom
  if command -v openssl &>/dev/null; then
    JWT_SECRET=$(openssl rand -hex 32)
  else
    JWT_SECRET=$(cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
  fi

  cat > "$ENV_FILE" <<EOF
# OpenResolve — generated by setup.sh on $(date)
# Do not commit this file to version control.

HOST_PORT=${HOST_PORT}
JWT_SECRET=${JWT_SECRET}
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

  echo "  ✓ .env created with a secure JWT secret."
fi

# ── Pull / build images ───────────────────────────────────────────────
echo "  → Building images (first run takes a few minutes)..."
docker compose build --quiet

# ── Start ─────────────────────────────────────────────────────────────
echo "  → Starting OpenResolve..."
docker compose up -d

# ── Wait for health ───────────────────────────────────────────────────
echo "  → Waiting for backend to be ready..."
MAX_WAIT=60
ELAPSED=0
until docker inspect openresolve-backend --format='{{.State.Health.Status}}' 2>/dev/null | grep -q "healthy"; do
  sleep 2
  ELAPSED=$((ELAPSED + 2))
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    echo ""
    echo "  ⚠  Backend is taking longer than expected."
    echo "     Check logs with: docker compose logs backend"
    break
  fi
done

# ── Done ──────────────────────────────────────────────────────────────
PORT=$(grep "^HOST_PORT=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "$HOST_PORT")
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║  OpenResolve is running!                     ║"
echo "  ║                                              ║"
echo "  ║  URL:       http://localhost:${PORT}             ║"
echo "  ║  Username:  admin                            ║"
echo "  ║  Password:  ${ADMIN_PASSWORD}                     ║"
echo "  ║                                              ║"
echo "  ║  Stop:    docker compose down                ║"
echo "  ║  Logs:    docker compose logs -f             ║"
echo "  ║  Backup:  ./backup.sh                        ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
